build:
    dependencies:
        before:
          - pip install etlt
          - pip install pytz
          - pip install coverage

    tests:
        override:
            -
                command: coverage run -m unittest discover -s test -p *Test.py
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'

checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    excluded_paths:
        - test/*

tools:
    pylint:
        python_version: '3'
        config_file: pylintrc
